[package]
name = "autosplitter-project-terra"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enigo = "*"
notify = "6.1.1"
dirs-next = "2.0"
